################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c \
C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c 

OBJS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_mmc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.o 

C_DEPS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_mmc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_mmc.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_mmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_mmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rtc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_sd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.o: C:/Projetos/Agro/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_sdmmc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

