################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/bsp.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/common.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/debug.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/flash_if.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/fw_update_app.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_gpio.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_i2c.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_rtc.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_spi.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_timer.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/main.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/mpu.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/sdio.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/sfu_app_new_image.c \
C:/Projetos/Agro/Projects/Curral/Core/src/stm32f4xx_hal_msp.c \
C:/Projetos/Agro/Projects/Curral/Core/src/stm32f4xx_hw.c \
C:/Projetos/Agro/Projects/Curral/Core/src/stm32f4xx_it.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/test_protections.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/vcom.c \
C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/ymodem.c 

OBJS += \
./Projects/bsp.o \
./Projects/common.o \
./Projects/debug.o \
./Projects/flash_if.o \
./Projects/fw_update_app.o \
./Projects/hw_gpio.o \
./Projects/hw_i2c.o \
./Projects/hw_rtc.o \
./Projects/hw_spi.o \
./Projects/hw_timer.o \
./Projects/main.o \
./Projects/mpu.o \
./Projects/sdio.o \
./Projects/sfu_app_new_image.o \
./Projects/stm32f4xx_hal_msp.o \
./Projects/stm32f4xx_hw.o \
./Projects/stm32f4xx_it.o \
./Projects/test_protections.o \
./Projects/vcom.o \
./Projects/ymodem.o 

C_DEPS += \
./Projects/bsp.d \
./Projects/common.d \
./Projects/debug.d \
./Projects/flash_if.d \
./Projects/fw_update_app.d \
./Projects/hw_gpio.d \
./Projects/hw_i2c.d \
./Projects/hw_rtc.d \
./Projects/hw_spi.d \
./Projects/hw_timer.d \
./Projects/main.d \
./Projects/mpu.d \
./Projects/sdio.d \
./Projects/sfu_app_new_image.d \
./Projects/stm32f4xx_hal_msp.d \
./Projects/stm32f4xx_hw.d \
./Projects/stm32f4xx_it.d \
./Projects/test_protections.d \
./Projects/vcom.d \
./Projects/ymodem.d 


# Each subdirectory must supply rules for building sources it contributes
Projects/bsp.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/bsp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/bsp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/common.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/common.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/debug.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/debug.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/debug.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/flash_if.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/flash_if.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/flash_if.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/fw_update_app.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/fw_update_app.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/fw_update_app.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/hw_gpio.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/hw_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/hw_i2c.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/hw_i2c.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/hw_rtc.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/hw_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/hw_spi.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/hw_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/hw_timer.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/hw_timer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/hw_timer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/main.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/mpu.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/mpu.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/mpu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/sdio.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/sdio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/sdio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/sfu_app_new_image.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/sfu_app_new_image.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/sfu_app_new_image.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/stm32f4xx_hal_msp.o: C:/Projetos/Agro/Projects/Curral/Core/src/stm32f4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/stm32f4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/stm32f4xx_hw.o: C:/Projetos/Agro/Projects/Curral/Core/src/stm32f4xx_hw.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/stm32f4xx_hw.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/stm32f4xx_it.o: C:/Projetos/Agro/Projects/Curral/Core/src/stm32f4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/stm32f4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/test_protections.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/test_protections.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/test_protections.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/vcom.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/vcom.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/vcom.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Projects/ymodem.o: C:/Projetos/Agro/Projects/Curral/LoRaWAN/App/src/ymodem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F407xx -DUSE_CHAFON_4_ANTENNAS -DUSE_STM32F4XX_NUCLEO -DUSE_HAL_DRIVER -DREGION_AU915 '-DACTIVE_REGION=LORAMAC_REGION_AU915' -c -I../../../Core/inc -I../../../../../Middlewares/ST/STM32_Secure_Engine/Core -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Basic -I../../../../../Drivers/BSP/Components/fonkan -I../../../../../Drivers/BSP/Components/chafon -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler/packages -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced/LmHandler -I../../../../../Middlewares/Third_Party/LoRaWAN/Patterns/Advanced -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac/region -I../../../LoRaWAN/App/inc -I../../../../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../../../../Drivers/BSP/STM32F4xx_Nucleo -I../../../../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../../Middlewares/Third_Party/FatFs/src -I../../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../../Middlewares/Third_Party/LoRaWAN/Phy -I../../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A1 -I../../../../../Drivers/BSP/X_NUCLEO_IKS01A2 -I../../../../../Drivers/BSP/Components/Common -I../../../../../Drivers/FATFS/App -I../../../../../Drivers/FATFS/Target -I../../../../../Drivers/BSP/Components/station -I../../../../../Drivers/BSP/Components/hts221 -I../../../../../Drivers/BSP/Components/lps22hb -I../../../../../Drivers/BSP/Components/lps25hb -I../../../../../Drivers/BSP/Components/sx1276 -I../../../../../Drivers/BSP/sx1276mb1mas -I../../../../../Projects/Bootloader/Linker_Common/SW4STM32 -I../../../../../Projects/Bootloader/2_Images_SECoreBin/Inc -I../../../../../Projects/Bootloader/2_Images_SBSFU/SBSFU/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Projects/ymodem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

